development:
  adapter: postgresql
  database: personal_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: personal_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: personal_production
  pool: 5
  timeout: 5000